version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8001:8001"
    working_dir: /app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - ./api:/app
    environment:
      - PYTHONPATH=/app

  agent:
    build: ./agent
    ports:
      - "8000:8000"
    working_dir: /app
    command: uvicorn app.service:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./agent:/app
    environment:
      - PYTHONPATH=/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8001
    depends_on:
      - api