openapi: 3.0.0
info:
  title: Hotel Agent Chat API
  version: 1.0.0
  description: API for chatting with the Guardio Hotel Booking agent and handling authentication callbacks.

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /callback:
    get:
      summary: Authentication callback
      description: Callback endpoint for authentication flow
      parameters:
        - in: query
          name: code
          schema:
            type: string
          required: true
          description: Authentication code
        - in: query
          name: state
          schema:
            type: string
          required: true
          description: State parameter for verification
      responses:
        '200':
          description: Successfully authenticated
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Invalid state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /health:
    get:
      summary: Health check
      description: Check if the API service is running correctly
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The message from the user
        threadId:
          type: string
          description: Optional thread ID
          nullable: true

    Response:
      type: object
      properties:
        chat_response:
          type: string
          nullable: true
          description: Text response from the agent
        tool_response:
          type: object
          nullable: true
          description: Response from any tools used by the agent

    ChatResponse:
      type: object
      properties:
        response:
          $ref: '#/components/schemas/Response'
        frontend_state:
          type: string
          description: Current state for the frontend
        message_states:
          type: array
          items:
            type: string
          description: States of messages in the conversation

    Error:
      type: object
      properties:
        detail:
          type: string
          description: Error message

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication